create_bd_cell -type ip -vlnv xilinx.com:ip:zynq_ultra_ps_e:3.4 sys_ps8

set_property CONFIG.PSU__USE__IRQ1 {1} [get_bd_cells sys_ps8]
set_property CONFIG.PSU__USE__S_AXI_GP2 {1} [get_bd_cells sys_ps8]
set_property CONFIG.PSU__USE__S_AXI_GP3 {1} [get_bd_cells sys_ps8]
set_property CONFIG.PSU__SAXIGP2__DATA_WIDTH {32} [get_bd_cells sys_ps8]
set_property CONFIG.PSU__SAXIGP3__DATA_WIDTH {32} [get_bd_cells sys_ps8]
set_property CONFIG.PSU__FPGA_PL0_ENABLE 1 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__CRL_APB__PL0_REF_CTRL__SRCSEL {IOPLL} [get_bd_cells sys_ps8]
set_property CONFIG.PSU__CRL_APB__PL0_REF_CTRL__FREQMHZ 100 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__FPGA_PL1_ENABLE 1 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__FPGA_PL2_ENABLE 1 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__CRL_APB__PL1_REF_CTRL__SRCSEL {IOPLL} [get_bd_cells sys_ps8]
set_property CONFIG.PSU__CRL_APB__PL1_REF_CTRL__FREQMHZ 250 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__CRL_APB__PL2_REF_CTRL__SRCSEL {IOPLL} [get_bd_cells sys_ps8]
set_property CONFIG.PSU__CRL_APB__PL2_REF_CTRL__FREQMHZ 500 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__SPI0__PERIPHERAL__ENABLE 1 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__SPI0__PERIPHERAL__IO {EMIO} [get_bd_cells sys_ps8]
set_property CONFIG.PSU__SPI0__GRP_SS1__ENABLE 1 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__SPI0__GRP_SS2__ENABLE 1 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__CRL_APB__SPI0_REF_CTRL__FREQMHZ 100 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__SPI1__PERIPHERAL__ENABLE 1 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__SPI1__PERIPHERAL__IO EMIO [get_bd_cells sys_ps8]
set_property CONFIG.PSU__SPI1__GRP_SS1__ENABLE 1 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__SPI1__GRP_SS2__ENABLE 1 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__CRL_APB__SPI1_REF_CTRL__FREQMHZ 100 [get_bd_cells sys_ps8]
set_property CONFIG.PSU__GPIO_EMIO__PERIPHERAL__ENABLE 1 [get_bd_cells sys_ps8]

apply_bd_automation -rule xilinx.com:bd_rule:zynq_ultra_ps_e -config {apply_board_preset 1}  [get_bd_cells sys_ps8]

set_property CONFIG.PSU__USE__IRQ0 {0} [get_bd_cells sys_ps8]

set_property CONFIG.PSU__MAXIGP0__DATA_WIDTH {32} [get_bd_cells sys_ps8]
set_property CONFIG.PSU__USE__M_AXI_GP1 {0} [get_bd_cells sys_ps8]
